### ISSUE TITLE
Change all images to jpg with white background for color inversion 

### ISSUE THREAD

**Issue by dygy** [mirea-pandahack/ithackmirea2018-landing#1]
Менюшка в верстке пропадает на 720 Ты хоть замени его тогда в бургер или пагинацию.

**Comment by dygy** [comment]
Есть еще проблемы с эмблемками спонсоров. К примеру Самсунг очень близко стоит к следующему спонсору. Также не рекомендую использовать png с черными буквами, потому что у людей с альтернативной rgb (темной темой и т.п.) буквы сливаются с фоном.

![image](https://user-images.githubusercontent.com/23248488/48956446-1f8e7d00-ef64-11e8-8b00-6015ab0cd5fc.png)

**Comment by lgg** [comment]
@dygy 
1. По поводу меню: не баг, а фича. С мобильного бургер будет неудобным, так как быстрее будет пролистать + прокрутка до нужного блока будет криво работать с открытым бургером.
2. По поводу >альтернативной rgb это как так вообще? 0о Что за настройки?
И не совсем понимаю решение проблемы, в случае, если логотип предоставлен партнёрами и согласно их дизайну - он должен быть чёрного цвета.

**Comment by dygy** [comment]
1. А. Не знал что все пункты меню на одной странице. Только там карта не оптимизируется. Я конечно не знаю как яндекс карты, но когда я вставлял гугловскую, то добился того, что она адаптировалась под размеры страницы достаточно красиво.
2.Сделай JPG с белым фоном и все будет ок. Странно что ты не знаешь про альтернативные цвета, но почти каждый сайт популярный оптимизируется под то, чтобы люди с приложухами вроде https://github.com/darkreader/darkreader могли спокойно сидеть на темной версии сайта.

**Comment by lgg** [comment]
@dygy 
1. На счёт карты - я потерял там параметр для оптимизации для мобилок при обновлении карты. Уже и в репо и на сайте фикс есть. У меня корректно отображает. Можешь проверить, пожалуйста, у тебя ок или остались проблемы?

2. Постараюсь.

**Comment by dygy** [comment]
На винде ок, на андроиде может не прогрузиться без перезагрузки страницы, но это скорее особенности виджета. Оно не выглядит просто как какое-то белое полотно, оно именно просто не появляется, словно там и не должно быть карты.
